package com.scratchio.crm.entity.enums;

public enum NotificationType {
    NEW_LEAD_ASSIGNED,
    LEAD_STATUS_CHANGED,
    FOLLOW_UP_REMINDER,
    TASK_DUE,
    TASK_COMPLETED,
    TASK_ASSIGNED,
    TASK_OVERDUE,
    MEETING_SCHEDULED,
    MEETING_CANCELLED,
    MEETING_COMPLETED,
    MEETING_REMINDER,
    CALL_REMINDER,
    DEAL_WON,
    DEAL_LOST,
    SYSTEM_ALERT,
    USER_MENTION
}
